import { Container, CssBaseline, ThemeProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import darkTheme from './dark.theme'
import './globals.css'
import Header from './header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider>
                    <ThemeProvider theme={darkTheme}>
                        <CssBaseline />
                        <Header />
                        <Container>{children}</Container>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
