import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import authenticated from './auth/authenticated'
import logout from './auth/logout'
import './globals.css'
import Header from './header/header'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const isAuthenticated = await authenticated()

    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <Providers authenticated={isAuthenticated}>
                        <div className="">
                            <Header logout={logout} />
                        </div>
                        <div>{children}</div>
                    </Providers>
                </div>
            </body>
        </html>
    )
}
